= bzlmod development guide
:toc:
:toclevels: 3

== Private/local registry

The easy way to create a private registry is to create a new github
repository, clone it to your local disk and then copy to it the
following elements from the
link:https://github.com/bazelbuild/bazel-central-registry[BCR]:

* `.bazelrc`
* `.bazelversion` (optional)
* `.gitignore`
* `MODULE.bazel` - edit to change the name.
* `WORKSPACE`
* `tools` - copy the entire subdirectory

You may also want to copy or create `AUTHORS`, `LICENSE`, and a readme file.

Create an empty `modules` directory.

Create an empty `work` directory.

=== --registry directives

To use your registry locally during development, put the following in
 `.bazelrc` (or a file it imports):

    common --registry=file:///path/to/registry
    common --registry=https://bcr.bazel.build

WARNING: You must add `--registry=https://bcr.bazel.build` as the last
directive. Bazel will not automatically use it if you use at least one
`--registry` record.

To test it over the network, you will need to push changes to your
registry and then use a `--registry` directive to redirect dependency
resolution to your github repository. To do this you must use a `raw`
github URL, e.g.:

    common --registry=https://raw.githubusercontent.com/<githubuid>/<repo>


A published bzlmod repository must not change; only additions are
allowed. But during development you may need to make changes to your
registry records as you go, and you do not want to publish a new
version for each change. So reserve the `main` branch of your
repository for releases, and use a `dev` branch for development.


During development, you will use the local copy of your repository by
specifying it in a `--registry` directive in one of your bazelrc
files. When you're ready for integration testing, use a `--registry`
directive that refers to the `dev` branch of your remote registry.

For example, if your registry repository is
`+https://github.com/<githubuid>/registry+`, and you cloned it to `$HOME/bzl/registry`, then during development you would use:

    common --registry=file:///home/<uid>/bzl/registry

For integration testing:

    common --registry=https://raw.githubusercontent.com/<githubuid>/registry/dev/

and to use released versions:

    common --registry=https://raw.githubusercontent.com/<githubuid>/registry/main/


You can control the use of these directives by putting them in
separate bazelrc files and passing some command line options; see
section [X] below for more details.


To create a `dev` branch:  from the root directory of your registry, run

    git switch -c dev


== Module development

Suppose you have developed Bazel module in `$HOME/mymodule`. To test
it locally using the `bzlmod` machinery, you need to create a record for
it in your local registry and then use that registry.

=== Create a local registry record

* In your registry create directory `work/mymodule`
* Copy the `MODULE.bazel` file for the module to `<reg>/work/mymodule/MODULE.bazel`

From the root directory of your registry, run:

    python3 ./tools/add_module.py

The `add_module` tool will prompt you for information. Here is an example, where the module name is `foobar`, the version is `1.2.3`, and the repo is `https://github.com/foo/foobar`:

----
INFO: Getting module information from user input...
ACTION: Please enter the module name: foobar
ACTION: Please enter the module version: 1.2.3
ACTION: Please enter the compatibility level [default is 1]: 0
ACTION: Please enter the URL of the source archive: https://github.com/foo/foobar/archive/refs/heads/master.zip
ACTION: Please enter the strip_prefix value of the archive [default None]: foobar-master
ACTION: Do you want to add patch files? [y/N]:
ACTION: Do you want to add a BUILD file? [y/N]:
ACTION: Do you want to specify a MODULE.bazel file? [y/N]: y
ACTION: Please enter the MODULE.bazel file path: work/foobar/MODULE.bazel
ACTION: Do you want to specify an existing presubmit.yml file? (See https://github.com/bazelbuild/bazel-central-registry/tree/main#presubmityml) [y/N]:
ACTION: Please enter a list of build targets you want to expose to downstream users, separated by `,`: //src:foobar
ACTION: Do you have a test module in your source archive? [Y/n]:
ACTION: Please enter the test module path in your source archive: //test
ACTION: Please enter a list of build targets for the test module, separated by `,`: //test
ACTION: Please enter a list of test targets for the test module, separated by `,`: //test
INFO: Saving module information to foobar.20230914-122132.json
INFO: You can use it via --input=foobar.20230914-122132.json
INFO: foobar is a new Bazel module...
ACTION: Please enter the homepage url for this module: https://github.com/foo/foobar
ACTION: Do you want to add a maintainer for this module? (See https://github.com/bazelbuild/bazel-central-registry/tree/main#module-maintainer) [y/N]:
----

If the source archive URL points to an unstable source (such as a github 'archive' url):

----
BcrValidationResult.FAILED: foobar@1.2.3 is using an unstable source url: `https://github.com/foo/foobar/archive/refs/heads/master.zip`.
You should use a release archive URL in the format of `https://github.com/<ORGANIZATION>/<REPO>/releases/download/<version>/<name>.tar.gz` to ensure the archive checksum stability.
See https://blog.bazel.build/2023/02/15/github-archive-checksum.html for more context.
----

You can ignore that during development. [TODO: link to the bazel message about this]

If the `MODULE.bazel` file you passed does not match the one accesible through the URL, you will get the following message:

----
BcrValidationResult.FAILED: Checked in MODULE.bazel file doesn't match the one in the extracted and patched sources.
Please fix the MODULE.bazel file or you can add the following patch to foobar@1.2.3:
----

This is expected during development since you may have changes that
you have not yet pushed to the origin repo. This is not a problem for
testing, so long as you use a `--repository` directive that points to
your local repository *AND* you use an override directive to point to
your local repo.

The `add_module.py` tool will add a registry record (in
`/path/to/registry/modules`); it will also create a json file that you
can use to update the record. The file name will be something like
`foobar.20230914-122132.json`. Move this file to
`/path/to/registry/work/foobar.json`.

=== Update a local registry record

When you are ready to update, copy your `MODULE.bazel` file to
`<reg>/work/foobar/MODULE.bazel` and run:

    python3 ./tools/add_module.py --input work/foobar.json

WARNING: if you make changes involving any of the information
contained in the json file you need to update it, or rerun
`add_module.py` without the `--input` argument.

== Overrides

[TODO]

* `--override_repository`
* the override "methods" (e.g. `archive_override`, `single_version_override`, etc.)

== Patching

[TODO]


== Testing

==== Clean build and test

Testing your Bazel module can be a little tricky. I mean testing the
"bzlmod-ness" of it, not testing your code.

So assume you've tested your code as you normally would and it's all
copacetic. Now you have to run tests to ensure that it is properly
integrated into the bzlmod system.

The complicating factors are that you have a private registry (such as a
github repo) and a local copy thereof, and you have some `--registry`
directives and possibly some `--override_repository` or other override
directives in some bazelrc files. Furthermore you may have multiple
bazelrc files. So in order to test properly you need to be able to
control all this stuff, so that you can build and tests in a clean environment.

For example, you may have:

* a _system rc_ file in `/etc/bazel.bazelrc` on Linux/MacOS, ` %ProgramData%\bazel.bazelrc` on Windows);

* a _workspace rc_ file, `.bazelrc` in your workspace root directory;

* a _home rc_ file, in `$HOME/.bazelrc` on Linux/MacOS; on Windows, `%USERPROFILE%\.bazelrc` if it exists, otherwise `%HOME%/.bazelrc`;

* according to link:https://bazel.build/run/bazelrc#global-bazelrc[The
  global bazelrc file], Bazel also looks for
  `$workspace/tools/bazel.rc`.

Furthermore you will likely have some additional bazelrc files, which
you will enable either using the `try-import` directive from within
another bazelrc file, or by passing `--bazelrc=_file_` on the command
line.

To control use of these files the following flags are availabel:

* `--nosystem_rc`
* `--noworkspace_rc`
* `--nohome_rc`
* `--bazelrc=_file_` - you can use this to specify a bazelrc to use while disabling all others; it is repeatble

You will also have:

* a local registry in `$HOME/path/to/registry`

* the network (github `origin` remote) version of your local registry, at `+https://github.com/<UID>/<REPO>+`

and you will have some `--repository` directives in your bazelrc files
to enable them.

(TODO: now describe the flags and options that ensure a "clean" env - `--no*_rc` etc.)

For prerelease and release, unit tests should be run in a clean
environment (`--nohome_rc` etc.), just like the builds.

=== Test phases


Testing your module goes in stages. You will want to build/use your
module from within its root directory, but for integration you will
need to create a separate Bazel project elsewhere on your system,
whose sole purpose is to depend on the module(s) your are developing.

TODO: flesh out the details of the bzlmod_test repo/workspace/module.
Summary: list your module as a `bazel_dep` in its MODULE.bazel file,
add an override for it, and then build it as an external resource by running
`bazel build @mymodule//path/to:target`

* module tests - run tests from your module's root directory, to
  verify that all `bazel_dep` directives resolve correctly.

NOTE: If you are simultaneously developing several modules you will
need to create registry records for all of them, and use `--registry`
and `--override_repository` directives to make sure your deps resolve
to your local copies during development. For example, this will be the
case if you decide to partition your module into several different
Bazel modules - something that the bzlmod system makes attractive.

* local test - use the local registry with a repo override to resolve
  dependencies on your module to your local repo.

* dev test - push your module changes, but use the local registry to
  resolve `bazel_dep` directives. The registry records refer to module
  resources on the network (i.e. without local overrides). This
  verifies that you've configured your registry properly by using it
  locally, before pushing it to the upstream registry repo.

* prerelease test - use the `dev` branch of your (private) network registry. This test verifies that you have correctly configured your registry by using it as a network resource.

* release test - use the `main` branch of your (private) network
registry. The release test is to verify that all is well after you
have installed your module's registry record to the `main` branch of
your registry.




=== local testing


=== prerelease testing

=== release testing

--bazelrc=/dev/null

--nokeep_state_after_build

== Release checklist

=== files

===== .bazelrc

Contains only:

        common --enable_bzlmod
        try-import .config/user.bazelrc

Everything else belongs in `.config/user.bazelrc` or some other
imported bazelrc file.

===== .bazelignore

Omit; add to `.gitignore`

===== .bazelversion

Omit; add to `.gitignore`

===== .config

The contents are gitignored, so this can be used by the developer for
private files, such as `.bazelrc`.

====== .config/.gitignore

Contains only `*` with newline. Users can use `git add -f .config/foo`
to force a file into version control.


====== .config/user.bazelrc

Do not put under version control. Suggested contents, in addition to
any customization:

    try-import .config/registries.bazelrc


===== .config/registries.bazelrc

This is where you put the `--registry` directives mentioned above.

===== .gitignore

    .bazelignore            <1>
    .bazelversion           <1>
    bazel-*                 <2>
    .bazel                  <3>
    *.gz                    <4>

<1> Bazel ignores these files _except_ for the root module
<1> The symlinks Bazel creates by default
<2>  In case you use `--symlink_prefix=.bazel/`
<3> The `bzlmod_release` tool (see below) will create a tarball; ignore it


===== //:BUILD.bazel

Omit this file if empty.

===== MODULE.bazel

Double-check `compatibility_level`.

_Do_ use the
link:https://bazel.build/rules/lib/globals/module#module[bazel_compatibility]
field to indicate which version of Bazel you have used for testing.

IMPORTANT: Also do test for compatibility; do not assume that your
module will build on x.0.0 just because it builds on x.y.z. (Example:
a `cc_shared_library` with a `deps` attribute will build with Bazel
`6.1.0` but not `6.0.0`.)

Depend on the latest versions of bcr modules if you can.

===== WORKSPACE.bazel

One comment line, #

===== test/MODULE.bazel

contains:
bazel_dep(name = "<module>")
local_path_override(module_name = "<module>", path = "..")

=== Verify build

(TODO: move these "clean build" instructions up into the build/test section. This part is just a checklist)

Use the bazelrc-cancelling directives (`--nohome_rc` etc) to ensure
that your build actions are not inadvertently affected by any
`bazelrc` files (such as `$HOME/.bazelrc`).

First run `bazel clean --expunge`.

Then use a dedicated bazelrc file to ensure your build uses exactly what you
need; for example you can define `.bazelrc.prerelease`,
`.bazelrc.release`, etc., each containing the appropriate
`--repository` and override directives.

Example:

    bazel --bazelrc=.bazelrc.prerelease --noworkspace_rc --nosystem_rc --nohome_rc build //...

where `.bazelrc.prerelease` contains something like

    common --enable_bzlmod
    common --registry=https://raw.githubusercontent.com/<UID>/registry/dev/  <1>
    common --registry=https://bcr.bazel.build

<1> NB: using the `dev` branch of your registry


The `no*_rc` directives will ensure that you do not inadvertently pick
up a `--registry` or override directive that might give you a false
positive.

[IMPORTANT]
====
Files like `.bazelrc.prerelease` can go anywhere in the
file system. If your are using one local registry to develope several
modules, it might be more convenient to use something like
`$HOME/.config/bazel/prerelease` and use it across projects:

    bazel build --bazelrc=~/.config/bazel/prerelease ... etc. ...
====

=== Cut a release

Commit your final changes and push. Then create a release archive by
running the following shell script:

[source,shell,title="bzlmod_release"]
----
    #!/bin/sh
    set -o errexit -o nounset -o pipefail
    MODULE=`buildozer 'print name' //MODULE.bazel:%module`
    VERSION=`buildozer 'print version' //MODULE.bazel:%module`
    PREFIX="${MODULE}-${VERSION}"
    ARCHIVE="${MODULE}-$VERSION.tar.gz"
    git archive --format=tar --prefix=${PREFIX}/ HEAD | gzip > $ARCHIVE
----

For module `foo` version `1.2.3` this will create `foo-1.2.3.tar.gz`.

On the github website create a release with tag. On the webpage you
should see a section that says `Attach binaries by dropping them here
or selecting them.` Do this for the tarball you just created. After
you click the "publish" you should see your tarball listed in the
`Assets` section of the ensuing webpage display.

CAUTION: Make sure the tag you create on the github UI matches the version identifier used for your tarball.

After you've cut a release, run release tests as described above,
using `--bazelrc=.bazelrc.release` containing

    common --enable_bzlmod
    common --registry=https://raw.githubusercontent.com/<UID>/registry/main/    <1>
    common --registry=https://bcr.bazel.build

<1> NB: using the `main` branch of your registry


== misc

TODO:

* bazel build //... must succeed WITHOUT any overrides or local
  registries. Build cmd should have --nohome_rc etc. also
  `--nokeep_state_after_build` instructs Bazel to "...discard
  the inmemory state from this build when the build finishes.
  Subsequent builds will not have any incrementality with respect to
  this one." This should go in the testing bazelrc files
  (`.bazel.prerelease` etc.)

* run `bazel clean --expunge` before `bazel build //...`

* make final commit, merge into main
* push
* make release archive by running ~/bzlmod_release

* cut release on github, uploading release archive
* get the url for the release archive (from assets section)
* registry:
        - copy MODULE.bazel
        - edit work/<lib>.json
            - compatibility_level
            - strip_prefix
            - url
            - version
        this fixes source.json:url to point to archive release
        - run add_module.py --input
          should report no errors
    * test registry record in test/bzlmod by using
      --registry=/path/to/registry
      and without --registry=https://raw.githubusercontent.com/<ID>/registry/main/


=== presubmit.yml

link:https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#using-a-specific-version-of-bazel[specific bazel version]

